Traceback (most recent call last):
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/vonw/anaconda3/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import requests
url = 'http://berkeleyearth.lbl.gov/auto/Global/Gridded/Land_and_Ocean_LatLong1.nc'
r = requests.get(url, allow_redirects=True)
open('Land_and_Ocean_LatLong1.nc').write(r.content)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m      2[0m url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttp://berkeleyearth.lbl.gov/auto/Global/Gridded/Land_and_Ocean_LatLong1.nc[39m[38;5;124m'[39m
[1;32m      3[0m r [38;5;241m=[39m requests[38;5;241m.[39mget(url, allow_redirects[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m----> 4[0m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mLand_and_Ocean_LatLong1.nc[39;49m[38;5;124;43m'[39;49m[43m)[49m[38;5;241m.[39mwrite(r[38;5;241m.[39mcontent)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'Land_and_Ocean_LatLong1.nc'
FileNotFoundError: [Errno 2] No such file or directory: 'Land_and_Ocean_LatLong1.nc'

